variable "cluster_name" {}
variable "cluster_endpoint" {}
variable "cluster_certificate_authority_data" {}
variable "worker_image" {}
variable "dask_worker_count" {}
variable "dask_worker_mb_ram" {}
variable "dask_worker_milli_cpu" {}
variable "dask_scheduler_mb_ram" {}
variable "dask_scheduler_milli_cpu" {}
variable "jupyter_mb_ram" {}
variable "jupyter_milli_cpu" {}
variable "jupyter_gb_storage" {}
variable "jupyter_volume_id" {}
