variable "cluster_name" {}
variable "cluster_region" {}
variable "cluster_version" {}
variable "stable_instance_type" {}
variable "spot_instance_type" {}
variable "spot_node_count" {}
variable "config_map_output_path" {}
variable "kubeconfig_output_path" {}
variable "jupyter_volume_gb" {}
